apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent-clusterrolebinding-edu25
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: edu25
roleRef:
  kind: ClusterRole
  name: elastic-agent-clusterrole
  apiGroup: rbac.authorization.k8s.io