apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-snapshot-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client