apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /q/metrics # Get metrics from URI /q/metrics
    scheme: http
  selector:
    matchLabels:
      app: backend # select only label app = backend