apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent-cluster-admin
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: elastic-daemonset
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---