apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-user-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-role-binding
subjects:
  - kind: User
    name: dev25
roleRef:
  kind: Role
  name: dev-user-role
  apiGroup: rbac.authorization.k8s.io