apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-example-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-example-role-binding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: sa-example-role
  apiGroup: rbac.authorization.k8s.io