server:
  port: 8888
  
spring:     
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console        
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    
  kafka:
    bootstrap-servers:
    - kafka:9092
    consumer:
      group-id: consumerGroupId
      auto-offset-reset: earliest
      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:      
       ack-mode: MANUAL_IMMEDIATE
   
      
